insert into public.lodges (name, description, image_path)
values
  ('Gamshütte', 'Simple trailhead hut on the Berliner Höhenweg in the Zillertal Alps.', null),
  ('Friesenberghaus', 'Memorial hut above the Friesenbergsee and a stop on the Berliner Höhenweg.', null),
  ('Olpererhütte', 'Well-known hut below the Olperer and a base for hikes in the Zillertal Alps.', null),
  ('Furtschlaglhaus', 'High alpine base between the Schlegeis reservoir and the high peaks of the Zillertal Alps.', null),
  ('Berliner Hütte', 'Historic, listed alpine hut in the upper Zemmgrund, surrounded by high Zillertal peaks.', 'berliner_hutte.jpg'),
  ('Greizer Hütte', 'High-mountain hut at the end of the Floitengrund, close to the Floitenkees.', null),
  ('Kasseler Hütte', 'Popular hut at the head of the Stilluptal and a good goal for day trips and traverses.', null),
  ('Karl-von-Edel-Hütte', 'Key base below the Ahornspitze and a classic stop on the Berliner Höhenweg.', null),
  ('Starkenburger Hütte', 'Scenic Stubaier hut with wide views over the Serles ridge and the Stubai main chain.', null),
  ('Franz-Senn-Hütte', 'Large, well-equipped hut in the Hinteres Oberbergtal and a classic Stubai base.', null),
  ('Neue Regensburger Hütte', 'Well-equipped hut above the Falbesoner Ochsenalm, known for its vegetarian kitchen.', null),
  ('Dresdner Hütte', 'Large all-season hut below the Stubai Glacier, used by hikers and skiers alike.', null),
  ('Sulzenauhütte', 'Popular day and stage stop above the Sulzenaualm on the Stubaier Höhenweg.', null),
  ('Nürnberger Hütte', 'High alpine base near the main ridge, with routes toward the Stubai glacier region.', null),
  ('Bremer Hütte', 'High-altitude hut under the Inneren Wetterspitze in a protected part of the Stubai Alps.', null),
  ('Innsbrucker Hütte', 'Sunny hut under the Habicht that serves hikers and climbers in the Stubai Alps.', null),
  ('Potsdamer Hütte', 'Family-friendly hut in the Fotschertal and a common start to the Sellrain hut circuit.', null),
  ('Alpengasthof Praxmar', 'Quiet mountain inn in the Lüsenstal, used as a base by hikers and ski tourers.', null),
  ('Westfalenhaus', 'Renovated Sellrain hut with views to the Längentalferner and the Lüsener Fernerkogel.', null),
  ('Pforzheimer Hütte', 'Urig high-mountain hut above the Gleirschtal and a base for 3000-meter tours.', null),
  ('Schweinfurter Hütte', 'Popular summer and winter base in the Horlachtal on the Sellrain and Ötztal routes.', null),
  ('Dortmunder Hütte', 'All-season hut in Kühtai near the Kühtaisattel, used for tours and winter sports.', null),
  ('Winnebachseehütte', 'Lakeside hut above Gries in Sulztal, reached past a waterfall on a family-friendly trail.', null),
  ('Bielefelder Hütte', 'Sociable hut under the Acherkogel with a sunny terrace and a relaxed mountain stop vibe.', null),
  ('Peter-Anich-Hütte', 'Small seasonal hut and day-hike base in the northern Stubai Alps near Telfs.', null),
  ('Geraer Hütte', 'Classic Zillertal base at the end of the Valsertal and a key stop on the Peter-Habeler-Runde.', null),
  ('Tuxerjochhaus', 'High hut below the Tuxer Joch with wide views and a central position on the Peter-Habeler-Runde.', null),
  ('Pfitscherjochhaus', 'High mountain hut on the border ridge between the Zillertal and South Tyrol, reached on the Peter-Habeler-Runde.', null),
  ('Landshuter Europahütte', 'Border hut on the Tuxer Hauptkamm and the western anchor of the Peter-Habeler-Runde.', null),
  ('Patscherkofel Schutzhaus', 'Start hut on the Inntaler Höhenweg above Innsbruck and a gateway to the Zirbenweg.', null),
  ('Glungezer-Hütte', 'Highest hut on the Inntaler Höhenweg and a landmark stop above the Inn Valley.', null),
  ('Lizumer Hütte', 'Remote hut in the Wattentaler Lizum and the next stop after the Glungezer section.', null),
  ('Weidener Hütte', 'Friendly hut on the Nafingalm and a central stop on the Inntaler Höhenweg.', null),
  ('Rastkogelhütte', 'Panoramic hut beneath the Rastkogel and the fourth hut on the Inntaler Höhenweg.', null),
  ('Kellerjoch-Hütte', 'Summit-side hut above Schwaz that closes the Inntaler Höhenweg.', null);
